### ISSUE TITLE
Changes for Logstash 5.3

### ISSUE THREAD

**Issue by tbernhardson** [HASecuritySolutions/Logstash#2]
Building out a system after taking SEC555 in San Diego last week (excellent class Seth).  There are a number of changes to the configurations as part of Logstash 5.0+ (with event['variable'] being deprecated and replaced with event.get('variable') and event.set('variable') ).  I can provide the diffs, files or (if you give me access) setup a Logstash 5 fork...  let me know how I can help.

**Comment by tbennett6421** [comment]
I've noticed this as well, I was planning on taking those file and duplicating them in a new folder in the repo for logstash 5+, fixing the changes and submitting a pull request.

**Comment by SMAPPER** [comment]
Most of these are fixed and I am building out updates for Elastic version 6. It changes things quite a bit but the changes will be backward compatible with Elastic 5.x. However, the current 5.x configs are not compatible with 6.X
