### ISSUE TITLE
Geo IP Database [ERROR 404]

### ISSUE THREAD

**Issue by unresolvedhost** [HASecuritySolutions/Logstash#8]
Can you give me alternate links to download Geo IP databases these links are not working
sudo wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
sudo wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
sudo wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
sudo wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
sudo wget http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz

**Comment by SMAPPER** [comment]
If this is for Logstash you can opt not to download any geoip databases and
simply use the ones built into the solution. Alternatively, you can
download newer databases from here:

https://dev.maxmind.com/geoip/geoip2/geolite2/

Sincerely,

Justin Henderson
(312) 857-5755
Systems and Security Architect
GSE # 108, Cyber Guardian Red / Blue
http://www.linkedin.com/in/justinhenderson2014/

**Comment by unresolvedhost** [comment]
https://github.com/SMAPPER/Logstash-Configs Are these configuration files compatible with the logstash 6.7.0

**Comment by SMAPPER** [comment]
If they are mmdb files,  yes.

**Comment by unresolvedhost** [comment]
Okay Thank You

**Comment by RichardPhilipsRoy** [comment]
sudo /usr/share/elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-translate
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-tld
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-elasticsearch
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-rest
sudo /opt/kibana/bin/kibana plugin --install elastic/sense
sudo /opt/kibana/bin/kibana plugin --install prelert_swimlane_vis -u https://github.com/prelert/kibana-swimlane-vis/archive/v0.1.0.tar.gz
cd ~
git clone https://github.com/oxalide/kibana_metric_vis_colors.git
sudo apt-get install zip -y
zip -r kibana_metric_vis_colors kibana_metric_vis_colors



These plugins are they available in X-Pack?

**Comment by unresolvedhost** [comment]
When modifying  /etc/logstash/conf.d/suricata.conf, /etc/logstash/conf.d/bro_http.conf do I need to create a new config files or do I need to modify the existing 6400_suricate.conf file,1106_preprocess_bro_http.conf?

I'm having trouble installing these plugins in  ELK 6.7.1 please help!
 
sudo /usr/share/elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-translate
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-tld
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-elasticsearch
sudo /opt/logstash/bin/logstash-plugin install logstash-filter-rest
sudo /opt/kibana/bin/kibana plugin --install elastic/sense
sudo /opt/kibana/bin/kibana plugin --install prelert_swimlane_vis -u https://github.com/prelert/kibana-swimlane-vis/archive/v0.1.0.tar.gz
cd ~
git clone https://github.com/oxalide/kibana_metric_vis_colors.git
sudo apt-get install zip -y
zip -r kibana_metric_vis_colors kibana_metric_vis_colors

**Comment by SMAPPER** [comment]
The paths and plugins have changed for ELK 6.7 and do not match this
repository. Moving forward, I'm planning on updating things in the
github.com/HASecuritySolutions/elastic_stack repo. However, it will be a
bit before I update that repo from ELK 6.5 to 6.7 as 6.7 just came out and
it replaces some key plugins such as rest with new Logstash plugins like
http (official Elastic plugin).

Sincerely,

Justin Henderson
(312) 857-5755
Systems and Security Architect
GSE # 108, Cyber Guardian Red / Blue
http://www.linkedin.com/in/justinhenderson2014/
